// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjTVNYREO00i96sO0U3R9FFCQ2CRGu4zg',
    appId: '1:335171248118:android:f1c93d5c9449d070bff1d7',
    messagingSenderId: '335171248118',
    projectId: 'zoom-clone-firebase-45ac8',
    databaseURL: 'https://zoom-clone-firebase-45ac8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zoom-clone-firebase-45ac8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmOj9VkWaV7kQSxUASXaf7AL2h-NEzXH0',
    appId: '1:335171248118:ios:95cf650447d0c640bff1d7',
    messagingSenderId: '335171248118',
    projectId: 'zoom-clone-firebase-45ac8',
    databaseURL: 'https://zoom-clone-firebase-45ac8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zoom-clone-firebase-45ac8.firebasestorage.app',
    iosClientId: '335171248118-svkci79t4acc8hdocsnj6indr6j8k4m7.apps.googleusercontent.com',
    iosBundleId: 'com.pookieestimit.zoomCloneFirebase',
  );
}
